### ISSUE TITLE
not connected

### ISSUE THREAD

**Issue by runtimevic** [hijaaack/TcHmiMongoDBCoreServiceSample#2]
Hello @hijaaack,
Not connected MongoDB, attach images:

<img width="931" alt="HMI_TE2000_MongoDB_Not_Connect" src="https://user-images.githubusercontent.com/53791834/237053813-50de1cae-13b2-4981-b051-ce8f5bf4dffb.PNG">

<img width="506" alt="HMI_TE2000_MongoDB_Not_Connect_Authentication" src="https://user-images.githubusercontent.com/53791834/237053852-47412f30-9db1-4f47-b65f-0f89aac5c178.PNG">

thanks you, Víctor.

**Comment by hijaaack** [comment]
I guess your URI is wrong. You need to specify the username and password for the remote connection.
https://www.mongodb.com/docs/manual/reference/connection-string/

**Comment by runtimevic** [comment]
> I guess your URI is wrong. You need to specify the username and password for the remote connection. https://www.mongodb.com/docs/manual/reference/connection-string/

Hello @hijaaack
Where can I put the username and password for the remote connection?, within the HMI TE2000 project
thank you

**Comment by runtimevic** [comment]
> I guess your URI is wrong. You need to specify the username and password for the remote connection. https://www.mongodb.com/docs/manual/reference/connection-string/

Hello @hijaaack ,
not connected is attach image:
<img width="577" alt="HMI_TE2000_MongoDB_Not_Connect_2" src="https://github.com/hijaaack/TcHmiMongoDBCoreServiceSample/assets/53791834/26ce9a12-58c3-4d6a-b485-ed63ed9c50bd">

**Comment by hijaaack** [comment]
looks like you have a whitespace before the port

**Comment by runtimevic** [comment]
> parece que tienes un espacio en blanco antes del puerto
- I had not noticed the white space, everything is ok, it works
- I have put you in another issue that would be very good to have a button to check the connection..
- you can close this issue,
<img width="958" alt="HMI_TE2000_MongoDB_Connected" src="https://github.com/hijaaack/TcHmiMongoDBCoreServiceSample/assets/53791834/9dc7ca58-5cb8-4269-ab0a-efe0eea2fa7f">

**Comment by hijaaack** [comment]
Glad it works, will close it! :)
